//  <auto-generated/> 
using Rido.IoTClient;

namespace dtmi_rido_pnp;

public class Cmd_getRuntimeStats_Response : BaseCommandResponse
{
    public Dictionary<string, string> diagnosticResults { get; set; } = new Dictionary<string, string>();
}
