//  <auto-generated/> 
using Rido.IoTClient.AzIoTHub.TopicBindings;


namespace dtmi_rido_pnp;

public class Cmd_getRuntimeStats_Response : BaseCommandResponse
{
    public Dictionary<string, string> diagnosticResults { get; set; } = new Dictionary<string, string>();
}
