//  <auto-generated/> 
using Rido.IoTClient;
using System.Text.Json;

namespace dtmi_rido_pnp;

public enum DiagnosticsMode
{
    minimal = 0,
    complete = 1,
    full = 2
}

public class Cmd_getRuntimeStats_Request : IBaseCommandRequest<Cmd_getRuntimeStats_Request>
{
    public DiagnosticsMode DiagnosticsMode { get; set; }

    public Cmd_getRuntimeStats_Request DeserializeBody(string payload)
    {
        return new Cmd_getRuntimeStats_Request()
        {
            DiagnosticsMode = JsonSerializer.Deserialize<DiagnosticsMode>(payload)
        };
    }
}


