//  <auto-generated/> 

using MQTTnet.Client;
using Rido.IoTClient;
using Rido.IoTClient.AzIoTHub;
using Rido.IoTClient.AzIoTHub.TopicBindings;

namespace dtmi_rido_pnp
{
    public class memmon : HubClient
    {
        const string modelId = "dtmi:rido:pnp:memmon;1";

        public ReadOnlyProperty<DateTime> Property_started;
        public WritableProperty<bool> Property_enabled;
        public WritableProperty<int> Property_interval;
        public TelemetryBinder<double> Telemetry_workingSet;
        public CommandBinder<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats;

        private memmon(IMqttClient c, ConnectionSettings cs) : base(c, cs)
        {
            Property_started = new ReadOnlyProperty<DateTime>(c, "started");
            Property_interval = new WritableProperty<int>(c, "interval");
            Property_enabled = new WritableProperty<bool>(c, "enabled");
            Telemetry_workingSet = new TelemetryBinder<double>(c, cs.DeviceId, "workingSet");
            Command_getRuntimeStats = new CommandBinder<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response>(c, "getRuntimeStats");
        }

        public static async Task<memmon> CreateClientAsync(string connectionString, CancellationToken cancellationToken = default)
        {
            var cs = new ConnectionSettings(connectionString)
            {
                ModelId = modelId
            };
            IMqttClient mqtt = await HubClient.ConnectWithConnectsionSettings(cs, cancellationToken);
            var client = new memmon(mqtt, cs);
            client.InitialTwin = await client.GetTwinAsync(cancellationToken);
            return client;
        }
    }
}
