//  <auto-generated/> 

using adu_demo.adu;
using Rido.MqttCore.PnP;
using System.Text.Json;

namespace adu_demo
{
    public class stepResultMetadata
    {
        public int resultCode { get; set; }
        public int extendedResultCode { get; set; }
        public string resultDetails { get; set; }
    }

    public class installResultMetadata
    {
        public int resultCode { get; set; }
        public int extendedResultCode { get; set; }
        public string resultDetails { get; set; }
        public Dictionary<string,stepResultMetadata> stepResults { get; set; }

    }

    public class workflowMetadata
    {
        public int action { get; set; }
        public string id { get; set; }
        public DateTime retryTimeStamp { get; set; }
    }

    public class agentMetadata
    {
        public int state { get; set; }
        public string installedUpdateId { get; set; }
        public workflowMetadata workflow { get; set; }
    }

    public class serviceMetadata
    {
        public workflowMetadata workflow { get; set; }
        public string updateManifest { get; set; }
        public string updateManifestSignature { get; set; }
        public Dictionary<string,string> fileUrls { get; set; }

        public updateManifest UpdateManifestParsed { get => JsonSerializer.Deserialize<updateManifest>(updateManifest); }
    }

    public interface Ideviceupdate : IComponent
    {
        IWritableProperty<agentMetadata> Property_agent { get; set; }
        IWritableProperty<serviceMetadata> Property_service {  get; set; }
    }
}
