//  <auto-generated/> 

namespace adu_demo.adu;
public class UpdateId
{
    public string provider { get; set; }
    public string name { get; set; }
    public string version { get; set; }
}

public class Compatibility
{
    public string deviceManufacturer { get; set; }
    public string deviceModel { get; set; }
}

public class HandlerProperties
{
    public string installedCriteria { get; set; }
}

public class Step
{
    public string handler { get; set; }
    public List<string> files { get; set; }
    public HandlerProperties handlerProperties { get; set; }
}

public class Instructions
{
    public List<Step> steps { get; set; }
}

public class Hashes
{
    public string sha256 { get; set; }
}

public class FileInfo
{
    public string fileName { get; set; }
    public int sizeInBytes { get; set; }
    public Hashes hashes { get; set; }
}

//public class Files
//{
//    public F9fec76f10aede60e f9fec76f10aede60e { get; set; }
//}

public class updateManifest
{
    public string manifestVersion { get; set; }
    public UpdateId updateId { get; set; }
    public List<Compatibility> compatibility { get; set; }
    public Instructions instructions { get; set; }
    public Dictionary<string, FileInfo> files { get; set; }
    public DateTime createdDateTime { get; set; }
}

