//  <auto-generated/> 

using Rido.Mqtt.AzIoTClient;
using Rido.Mqtt.HubClient;
using Rido.Mqtt.HubClient.TopicBindings;
using Rido.MqttCore;
using Rido.MqttCore.PnP;
using System.Diagnostics;

namespace dtmi_rido_pnp
{
    public class memmon : HubMqttClient, Imemmon
    {
        const string modelId = "dtmi:rido:pnp:memmon;1";
        public string InitialState { get; set; }

        public IReadOnlyProperty<DateTime> Property_started { get; set; }
        public IWritableProperty<bool> Property_enabled { get; set; }
        public IWritableProperty<int> Property_interval { get; set; }
        public ITelemetry<double> Telemetry_workingSet { get; set; }
        public ICommand<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats { get; set; }

        //public IMqttBaseClient Connection;

        internal memmon(IMqttBaseClient c) : base(c)
        {
            Connection = c;
            Property_started = new ReadOnlyProperty<DateTime>(c, "started");
            Property_interval = new WritableProperty<int>(c, "interval");
            Property_enabled = new WritableProperty<bool>(c, "enabled");
            Telemetry_workingSet = new Telemetry<double>(c, "workingSet");
            Command_getRuntimeStats = new Command<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response>(c, "getRuntimeStats");
        }

        public static async Task<memmon> CreateClientAsync(string connectionString, CancellationToken cancellationToken = default)
        {
            var cs = connectionString + ";ModelId=" + modelId;
            
            //HubDpsFactory.OnReconnect += (o, e) =>
            //{
            //    var connection = (IMqttBaseClient)o;
            //    Trace.TraceInformation("Reconnection Status: " + connection.IsConnected);
            //    client = new memmon(connection);
            //};
            var hub = await HubDpsFactory.CreateFromConnectionStringAsync(cs);
            memmon client = new memmon(hub.Connection);
            client.InitialState = await client.GetTwinAsync(cancellationToken);
            return client;
        }
    }



}
