//  <auto-generated/> 

using adu_demo_hub;
using Rido.Mqtt.HubClient.TopicBindings;
using Rido.MqttCore;
using Rido.MqttCore.PnP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace dtmi_azure_iot
{
    public class deviceupdate : Component, Ideviceupdate
    {
        public IWritableProperty<agentMetadata> Property_agent { get; set; }
        public IWritableProperty<serviceMetadata> Property_service { get; set ; }
        public deviceupdate(IMqttBaseClient c, string name) : base(c, name)
        {
            Property_agent = new WritableProperty<agentMetadata>(c, "agent", name);
            Property_service = new WritableProperty<serviceMetadata>(c, "service", name);
        }


        public override Dictionary<string, object> ToJsonDict()
        {
            Dictionary<string, object> dict = new Dictionary<string, object>();
            return dict;
        }
    }
}
