//  <auto-generated/> 

using Rido.MqttCore.PnP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;

namespace adu_demo_hub
{
    public class stepResultMetadata
    {
        public int resultCode { get; set; }
        public int extendedResultCode { get; set; }
        public string resultDetails { get; set; }
    }

    public class installResultMetadata
    {
        public int resultCode { get; set; }
        public int extendedResultCode { get; set; }
        public string resultDetails { get; set; }
        public Dictionary<string,stepResultMetadata> stepResults { get; set; }

    }

    public class workflowMetadata
    {
        public int action { get; set; }
        public string id { get; set; }
        public DateTime retryTimeStamp { get; set; }
    }

    public class agentMetadata
    {
        public int state { get; set; }
        public string installedUpdateId { get; set; }
        public workflowMetadata workflow { get; set; }
    }

    public class serviceMetadata
    {
        public workflowMetadata workflow { get; set; }
        public string updateManifest { get; set; }
        public string updateManifestSignature { get; set; }
        public Dictionary<string,string> fileUrls { get; set; }
    }

    public interface Ideviceupdate
    {
        IWritableProperty<agentMetadata> Property_agent { get; set; }
        IWritableProperty<serviceMetadata> Property_service {  get; set; }
    }
}
