//  <auto-generated/> 
using Rido.MqttCore.PnP;

namespace dtmi.azure.DeviceManagement
{
    public interface DeviceInformation : IComponent
    {
        IReadOnlyProperty<string> Property_manufacturer { get; set; }
        IReadOnlyProperty<string> Property_model { get; set; }
        IReadOnlyProperty<string> Property_osName { get; set; }
        IReadOnlyProperty<string> Property_processorArchitecture { get; set; }
        IReadOnlyProperty<string> Property_processorManufacturer { get; set; }
        IReadOnlyProperty<string> Property_swVersion { get; set; }
        IReadOnlyProperty<long> Property_totalMemory { get; set; }
        IReadOnlyProperty<long> Property_totalStorage { get; set; }
    }
}