//  <auto-generated/> 

using dtmi.azure.DeviceManagement;
using dtmi.azure.iot;
using Rido.MqttCore.PnP;
using static dtmi.rido.pnp.memmon;

namespace dtmi.rido.pnp
{
    public interface memmon 
    {
        public enum DiagnosticsMode
        {
            minimal = 0,
            complete = 1,
            full = 2
        }
        public class Cmd_getRuntimeStats_Request : IBaseCommandRequest<Cmd_getRuntimeStats_Request>
        {
            public DiagnosticsMode DiagnosticsMode { get; set; }

            public Cmd_getRuntimeStats_Request DeserializeBody(string payload)
            {
                return new Cmd_getRuntimeStats_Request()
                {
                    DiagnosticsMode = System.Text.Json.JsonSerializer.Deserialize<DiagnosticsMode>(payload)
                };
            }
        }
        public class Cmd_getRuntimeStats_Response : BaseCommandResponse
        {
            public Dictionary<string, string> diagnosticResults { get; set; } = new Dictionary<string, string>();
        }

        public IReadOnlyProperty<DateTime> Property_started { get; set; }
        public IWritableProperty<bool> Property_enabled { get; set; }
        public IWritableProperty<int> Property_interval { get; set; }
        public ITelemetry<double> Telemetry_workingSet { get; set; }
        public ICommand<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats { get; set; }

        public deviceupdate Component_deviceUpdate { get; set; }
        public DeviceInformation Component_deviceInformation { get; set; }

    }
}
