//  <auto-generated/> 

using Rido.Mqtt.HubClient.TopicBindings;
using Rido.MqttCore;
using Rido.MqttCore.PnP;

namespace adu_demo_hub
{
    public class deviceupdate : Component, Ideviceupdate
    {
        public IWritableProperty<agentMetadata> Property_agent { get; set; }
        public IWritableProperty<serviceMetadata> Property_service { get; set ; }
        public deviceupdate(IMqttBaseClient c, string name) : base(c, name)
        {
            Property_agent = new WritableProperty<agentMetadata>(c, "agent", name);
            Property_service = new WritableProperty<serviceMetadata>(c, "service", name);
        }


        public override Dictionary<string, object> ToJsonDict()
        {
            Dictionary<string, object> dict = new Dictionary<string, object>();
            return dict;
        }
    }
}
