//  <auto-generated/> 
namespace dtmi_azure_devicemanagement
{
    public class DeviceInformation
    {
        public string __t { get; set; } = "c";
        public string manufacturer { get; set; }
        public string Manufacturer { get; internal set; }
        public string model { get; set; }
        public string softwareVersion { get; set; }
        public string operatingSystemName { get; set; }
        public string processorArchitecture { get; set; }
        public string processorManufacturer { get; set; }
        public long totalMemory { get; set; }
        public long totalStorage { get; set; }
    }
}
