name: Rido.IoTClient CI/CD

on:
  push:
    branches: [ master, dev ]
    tags:
    - "v*"
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_MYGET: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build tests/Rido.Mqtt.UnitTests
    - name: Pack
      run: dotnet pack -c Release -o _nupkgs
    - if: ${{ env.PUSH_MYGET }}
      name: Push MyGet
      run: cd _nupkgs && dotnet nuget push * --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/ridopackages/api/v2/package --skip-duplicate --no-symbols
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Push NUGET
      run: cd _nupkgs && dotnet nuget push * --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
